server {
    listen 443 ssl;
    server_name 3skici.com www.3skici.com;

    ssl_certificate /etc/letsencrypt/live/3skici.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/3skici.com/privkey.pem;

    root /var/www/3skici/build;
    index index.html;

    # Serve static files
    location /static {
        alias /var/www/3skici/build/static;
    }

    # Handle React routing
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Proxy API requests
    location /api {
        proxy_pass http://localhost:5000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
    }
}