name: Deploy to DigitalOcean Droplet

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /root/3skici-app
            git pull origin main
            npm install --prefix 3skici-backend
            npm install --prefix 3skici-frontend
            npm run build --prefix 3skici-frontend
            sudo rm -rf /var/www/3skici/build
            sudo mv 3skici-frontend/build /var/www/3skici/
            sudo chown -R www-data:www-data /var/www/3skici/build
            pm2 restart react-backend
            sudo systemctl restart nginx